import { expect, test } from "vitest";

import {
  createZennArticleTemplate,
  getArticleDescription,
  isVisibleArticle,
  parseZennArticleSource,
  toEsaMarkdown,
  toEsaPostPayload,
  toWebsiteArticleMetadata,
} from "./article";

test("creates an article that both Zenn and the website can load", () => {
  expect(createZennArticleTemplate(new Date("2026-08-04T15:00:00+09:00"))).toBe(`---
title: ""
emoji: "📝"
type: "tech"
topics: []
published: false
published_at: 2026-08-04
---

Write the article here.
`);
});

test("uses the first prose paragraph as the website description", () => {
  const markdown = `
## Introduction

This paragraph describes the article for cards and metadata.

The rest of the article follows.
`;

  expect(getArticleDescription(markdown)).toBe(
    "This paragraph describes the article for cards and metadata.",
  );
});

test("uses website image URLs in esa Markdown", () => {
  const markdown = "![Architecture](/images/article-publishing/architecture.png)";

  expect(
    toEsaMarkdown(markdown, {
      canonicalUrl: "https://furedea.com/ja/blog/article-publishing/",
    }),
  ).toContain("![Architecture](https://furedea.com/images/article-publishing/architecture.png)");
});

test("preserves image examples inside fenced code blocks", () => {
  const markdown = "```markdown\n![Example](/images/article/example.png)\n```";

  expect(
    toEsaMarkdown(markdown, {
      canonicalUrl: "https://furedea.com/ja/blog/article-publishing/",
    }),
  ).toContain(markdown);
});

test("attributes the esa copy to the canonical website article", () => {
  const canonicalUrl = "https://furedea.com/ja/blog/article-publishing/";

  expect(toEsaMarkdown("Article body.", { canonicalUrl })).toBe(
    `Article body.\n\n---\n\nOriginally published at ${canonicalUrl}`,
  );
});

test("converts Zenn messages to portable esa blockquotes", () => {
  const markdown = `:::message
Check all publication targets before release.
:::`;

  expect(
    toEsaMarkdown(markdown, {
      canonicalUrl: "https://furedea.com/ja/blog/article-publishing/",
    }),
  ).toContain("> **Note**\n>\n> Check all publication targets before release.");
});

test("maps Zenn article metadata to the website model", () => {
  const publishedAt = new Date("2026-08-04T00:00:00.000Z");

  expect(
    toWebsiteArticleMetadata(
      {
        title: "Publishing one article everywhere",
        emoji: "📝",
        type: "tech",
        topics: ["astro", "zenn"],
        published: true,
        published_at: publishedAt,
      },
      "The first paragraph becomes the website description.",
    ),
  ).toEqual({
    title: "Publishing one article everywhere",
    description: "The first paragraph becomes the website description.",
    date: publishedAt,
    tags: ["astro", "zenn"],
  });
});

test("parses the repository Zenn frontmatter format", () => {
  const source = `---
title: "Publishing one article everywhere"
emoji: "📝"
type: "tech"
topics: ["astro", "zenn"]
published: false
published_at: 2026-08-04
---

Article body.
`;

  expect(parseZennArticleSource(source)).toEqual({
    metadata: {
      title: "Publishing one article everywhere",
      emoji: "📝",
      type: "tech",
      topics: ["astro", "zenn"],
      published: false,
      published_at: new Date("2026-08-04T00:00:00.000Z"),
    },
    markdown: "\nArticle body.\n",
  });
});

test("accepts explanatory comments generated by Zenn CLI", () => {
  const source = `---
title: "A # character stays in the title" # article title
emoji: "📝" # one emoji
type: "tech" # tech or idea
topics: [] # up to five topics
published: false # draft
published_at: 2026-08-04
---
Body.
`;

  expect(parseZennArticleSource(source).metadata.title).toBe("A # character stays in the title");
});

test("maps a published Zenn article to a shipped esa post", () => {
  expect(
    toEsaPostPayload(
      {
        title: "Publishing one article everywhere",
        emoji: "📝",
        type: "tech",
        topics: ["astro", "zenn"],
        published: true,
        published_at: new Date("2026-08-04T00:00:00.000Z"),
      },
      "Article body.",
      {
        canonicalUrl: "https://furedea.com/ja/blog/article-publishing/",
        category: "blog",
      },
    ),
  ).toEqual({
    post: {
      name: "Publishing one article everywhere",
      body_md:
        "Article body.\n\n---\n\nOriginally published at https://furedea.com/ja/blog/article-publishing/",
      tags: ["astro", "zenn"],
      category: "blog",
      wip: false,
      message: "Sync from furedea.com.",
    },
  });
});

test("shows draft articles only when local previews include drafts", () => {
  expect(isVisibleArticle(false, true)).toBe(true);
  expect(isVisibleArticle(false, false)).toBe(false);
});
